Squashed commit of the following:
commit 8c45ba3574a2438b9d3cf416b99f37779492ab2a
Author: thomasinaz41213 <120696745+thomasinaz41213@users.noreply.github.com>
Date:   Wed Mar 13 14:15:40 2024 -0700

    Update version

commit 918f3e8268803a51c37b0e70f14e1dcd6be8dc7a
Author: thomasinaz41213 <120696745+thomasinaz41213@users.noreply.github.com>
Date:   Wed Mar 13 14:15:24 2024 -0700

    Update changes

commit 114dbc3e1299b0bb9ba4cb2a9a2e2862b1fabe6d
Author: thomasinaz41213 <120696745+thomasinaz41213@users.noreply.github.com>
Date:   Wed Mar 13 14:14:20 2024 -0700

    setup

commit c47d611b3cac136864aa0ac80f081c2873e2a97a
Author: thomasinaz41213 <120696745+thomasinaz41213@users.noreply.github.com>
Date:   Wed Mar 13 14:13:31 2024 -0700

    update setup

commit 9cd666ee9bbaac0f7c7c51662b7af44afb875758
Author: thomasinaz41213 <120696745+thomasinaz41213@users.noreply.github.com>
Date:   Wed Mar 13 14:01:39 2024 -0700

    Update version

commit ba6f6e67a016222f87699592c38dee1d6b242143
Author: thomasinaz41213 <120696745+thomasinaz41213@users.noreply.github.com>
Date:   Wed Mar 13 14:01:18 2024 -0700

    Update changes

commit 73f193ff14b72d18f36a765cabfb674f7e080382
Author: thomasinaz41213 <120696745+thomasinaz41213@users.noreply.github.com>
Date:   Wed Mar 13 14:00:44 2024 -0700

    Rename genericSetupScript to setup

commit 57013125e306c211a3b187406054a947d18f1793
Author: thomasinaz41213 <120696745+thomasinaz41213@users.noreply.github.com>
Date:   Wed Mar 13 13:56:23 2024 -0700

    Update version

commit 42a0a598e32564681ac0929a1bd49f0d9617ad03
Author: thomasinaz41213 <120696745+thomasinaz41213@users.noreply.github.com>
Date:   Wed Mar 13 13:56:04 2024 -0700

    Update changes

commit 8ec9479b82ce23f9d967ac3e477249a8d00182ad
Author: thomasinaz41213 <120696745+thomasinaz41213@users.noreply.github.com>
Date:   Wed Mar 13 13:42:34 2024 -0700

    Update version

commit 31f328bccf0334c32b92d48cc44ce9da95a50ac7
Author: thomasinaz41213 <120696745+thomasinaz41213@users.noreply.github.com>
Date:   Wed Mar 13 13:42:05 2024 -0700

    Update changes

commit 60a9791e151393f80cd7864be4417a83cd763d76
Author: thomasinaz41213 <120696745+thomasinaz41213@users.noreply.github.com>
Date:   Wed Mar 13 13:37:39 2024 -0700

    files

commit 05553bf21f62c4c8048edaa58967c9f1c6e575ec
Author: thomasinaz41213 <120696745+thomasinaz41213@users.noreply.github.com>
Date:   Wed Mar 13 13:27:28 2024 -0700

    update patch files

commit 4bf392c444d33d6f40504f494e8f66abc80a3d56
Author: thomasinaz41213 <120696745+thomasinaz41213@users.noreply.github.com>
Date:   Wed Mar 13 13:00:01 2024 -0700

    add orig file

commit 0d9706efb4466353a6973c24c99ce06c5e5b6b8f
Author: thomasinaz41213 <120696745+thomasinaz41213@users.noreply.github.com>
Date:   Wed Mar 13 12:30:01 2024 -0700

    add patch file

commit e151b3cc9b4ef7c947e4d50a0b52148ac935c115
Author: thomasinaz41213 <120696745+thomasinaz41213@users.noreply.github.com>
Date:   Wed Mar 13 12:14:33 2024 -0700

    add patching files

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,79 +1,34 @@
 #!/bin/bash
 
-# this script installs ContextStorage following SetupHelper rules (https://github.com/kwindrem/SetupHelper)
 #
-# this script will accept the following commands on the command line:
-#	setup install
-#	setup uninstall
+# this script will install any package that can use
+# the automated install and uninstall mechanisms provided by SetupHelper
+# that is, no custom prompting for command line exection
+#	and no custom installation such as editing replacement files
+#
+# link the package's setup script to this one:
+#	ln -s /data/SetupHelper/genericSetupScript /data/<package name>/setup
 
-packageLogFile="/var/log/ContextStorage/current"
+# tell CommonResources to:
+#	prompt for install/uninstall
+#	auto install or auto uninstall
+#	then exit
+#	CommonResources will NOT return here !
 
-#### following lines incorporate SetupHelper utilities into this script
-# Refer to the SetupHelper ReadMe file for details.
+standardPromptAndActions='yes'
 
-source "/data/SetupHelper/CommonResources"
-
-#### end of lines to include SetupHelper
-
-# GitHub account info - fill in as appropriate
-# to include this package in SetupHelper automatic updates
-packageGitHubUser="thomasinaz41213"
-packageGitHubBranch="main"
-
-restartSystemCalc=false
-
-#### running manually and OK to proceed - prompt for input
-if [ $scriptAction == 'NONE' ] ; then
-	echo
-	echo "Enabling Context Storage in Node Red"
-	echo
-	standardActionPrompt
+#### following lines incorporate helper resources into this script
+pkgDir=$( dirname $0 )
+pkgName=$( basename $pkgDir )
+pkgRoot=$( dirname $pkgDir )
+if [ -e "$pkgDir/HelperResources/IncludeHelpers" ]; then
+	source "$pkgDir/HelperResources/IncludeHelpers"
+elif [ -e "$pkgRoot/SetupHelper/HelperResources/IncludeHelpers" ]; then
+	source "$pkgRoot/SetupHelper/HelperResources/IncludeHelpers"
+else
+	echo "$pkgName: helper files not found - can't continue" | tee -a "/data/log/SetupHelper"
+	exit 1
 fi
+#### end of lines to include helper resources
 
-#### here to do the actual work
-
-
-if [ $scriptAction == 'INSTALL' ] ; then
-	logMessage "++ Installing ContextStorage"
-
-
-	updateActiveFile /usr/lib/node_modules/node-red/venus-settings.js
-
-	##
-
-	logMessage "++ $packageName installed"
-fi
-
-# #### uninstalling - check scriptAction again
-# if an install step failed package needs to be removed
-if [ $scriptAction == 'UNINSTALL' ] ; then
-    logMessage "++ Uninstalling ContextStorage"
-
-	
-	restoreActiveFile /usr/lib/node_modules/node-red/venus-settings.js
-	
-	
-	##
-	
-	restartSystemCalc=false
-		
-	logMessage "++ $packageName uninstalled"
-fi
-
-
-
-if $filesUpdated ; then
-    ##
-    ## Reboot or restart the services
-    ##
-    svc -d /service/node-red-venus ; svc -u /service/node-red-venus
-    restartGui=false
-fi
-
-if $restartSystemCalc ; then
-	logMessage "restarting systemcalc"
-	svc -t /service/dbus-systemcalc-py
-fi
-
-# thats all folks - SCRIPT EXITS INSIDE THE FUNCTION
-endScript
+# never returns from CommonResources !
